### ISSUE TITLE
Voando 🚀

### ISSUE THREAD

**Issue by lucasferreira** [leoconon/Jogo-da-Velha-Android#1]
Jovem Nonnenmacher, que tema massa cara... me surpreendeu haha

Uma velha que têm o seu próprio jogo, interessantíssimo. Mais de uma tela, persistencia de dados, usou o grid layout par fazer o 3x3 do jogo, muito bacana mesmo ideia show!

**Comment by leoconon** [comment]
> Jovem Nonnenmacher, que tema massa cara... me surpreendeu haha
> 
> Uma velha que têm o seu próprio jogo, interessantíssimo. Mais de uma tela, persistencia de dados, usou o grid layout par fazer o 3x3 do jogo, muito bacana mesmo ideia show!

Muito brigado mestre Lucas. Quando iniciei no mundo da programação tinha a "tradição" de fazer um jogo da velha ou uma calculadora, pois permitem a aplicação de vários conceitos e técnicas, exigindo uma busca de conhecimentos da ferramenta (desde elementos visuais a princípios da linguagem), sem ser tão maçante quanto formulários e sisteminhas.
